### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by zytlion** [SvenAugustus/Stellaris_Mod#1]
大佬，能更新吗？

**Comment by SvenAugustus** [comment]
> 大佬，能更新吗？

追到这里了啊~ (⊙﹏⊙)b

**Comment by zytlion** [comment]
Thanks for your effort, it has already been done.-------- 原始邮件 --------发件人： Zeno ***@***.***>日期： 2021年4月18日周日 01:53收件人： SvenAugustus/Stellaris_Mod ***@***.***>抄送： zytlion ***@***.***>, Author ***@***.***>主    题： Re: [SvenAugustus/Stellaris_Mod] 求更新 (#1)



大佬，能更新吗？



追到这里了啊~ (⊙﹏⊙)b

**Comment by SvenAugustus** [comment]
> Thanks for your effort, it has already been done.-------- 原始邮件 --------发件人： Zeno ***@***.***>日期： 2021年4月18日周日 01:53收件人： SvenAugustus/Stellaris_Mod ***@***.***>抄送： zytlion ***@***.***>, Author ***@***.***>主 题： Re: [SvenAugustus/Stellaris_Mod] 求更新 (#1) 大佬，能更新吗？ 追到这里了啊~ (⊙﹏⊙)b —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

updated.
